import './globals.css';
import type { Metadata } from 'next';
import { 
  // Inter, 
  Open_Sans } from 'next/font/google';

// const inter = Inter({ subsets: ['latin', 'cyrillic'] });
const openSansFont = Open_Sans({ subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
  title: 'My top app',
  description: 'Generated by create next app',

};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={openSansFont.className}>{children}</body>
    </html>
  );
}
